### PR TITLE
Upgrade react-autosuggest to 8.0.0

### PR DESCRIPTION
**Pull request by moroshko**
[`react-autosuggest` 8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0) removes `redux` and `react-redux` from its dependencies. This should reduce the size of the production js bundle.
Hello from Silicon Valley ✋

### CODE REVIEW

**Comment by mjt01** [comment]
Open Source Level: Boss 🏆 

Upgrading your package and sending PRs to consumers! You're the best. I'll give it a once over. Thanks mate 🙌

**Comment by moroshko** [comment]
I'm curious to know the effect it had on the production js bundle 🤔

**Comment by mjt01** [comment]
@moroshko the chalice production bundle dropped from 1654kb to 1649kb. It would probably have a bigger affect on projects that did not use redux/react-redux.

**Comment by moroshko** [comment]
Did you mean `mb` instead of `kb`?

**Comment by mjt01** [comment]
No, its not 1654mb! That's in kilobytes

**Comment by moroshko** [comment]
Oh, sorry, not sure what I was thinking 🤔

**Comment by markdalgleish** [comment]
@moroshko hello from SEEK! 👋 😄

**Comment by mengtzu** [comment]
Any reason not to merge this?  I installed react-autocomplete 8 and now I'm getting peer dependency complaints >_<

**Comment by markdalgleish** [comment]
@mengtzu could you post the exact error you're seeing?

**Comment by mengtzu** [comment]
`npm WARN EPEERINVALID seek-style-guide@13.1.1 requires a peer of react-autosuggest@^7.0.1 but none was installed.`

**Comment by markdalgleish** [comment]
I'd say it seems like this needs to be a regular dependency, not a peer. @mjt01 thoughts?

**Comment by mjt01** [comment]
Reason for it being a peer is otherwise every app would include `react-autosuggest` even if they weren't using that component. We definitely need to look at dependency management as a whole, but that should not be a blocker for this PR.

**Comment by markdalgleish** [comment]
Cool, sounds good to me. Given it's a major version bump for react-autosuggest, do we consider it a major version for the style guide too? Seems like the safest bet, and we're not scared of major versions over here 😄

**Comment by markdalgleish** [comment]
👍

**Pull request merged**
